package compose

import (
	"fmt"
	"path/filepath"
	"sort"
	"strings"

	"github.com/okfriansyah-moh/ares/internal/markdown"
	"github.com/okfriansyah-moh/ares/internal/safepath"
	"github.com/okfriansyah-moh/ares/pkg/arslib"
)

// CodexComposer writes AGENTS.md at the repository root.
type CodexComposer struct{}

func (c *CodexComposer) Target() string {
	return "codex"
}

func (c *CodexComposer) Compose(root string, repo *arslib.Repository) error {
	if repo == nil {
		return fmt.Errorf("compose codex: repository is nil")
	}

	if err := validateAgentIDs(root, repo.Agents); err != nil {
		return fmt.Errorf("compose codex: %w", err)
	}

	if _, err := safepath.Join(root, "AGENTS.md"); err != nil {
		return fmt.Errorf("compose codex: %w", err)
	}

	if err := resetDir(root, ".agents"); err != nil {
		return fmt.Errorf("compose codex: %w", err)
	}
	if err := resetDir(root, ".codex"); err != nil {
		return fmt.Errorf("compose codex: %w", err)
	}
	if err := safepath.MkdirAll(root, ".agents/skills", 0o755); err != nil {
		return fmt.Errorf("compose codex: %w", err)
	}
	if err := safepath.MkdirAll(root, ".codex/agents", 0o755); err != nil {
		return fmt.Errorf("compose codex: %w", err)
	}
	if err := safepath.MkdirAll(root, ".codex/rules", 0o755); err != nil {
		return fmt.Errorf("compose codex: %w", err)
	}

	skills := append([]arslib.Skill(nil), repo.Skills...)
	sort.Slice(skills, func(i, j int) bool {
		return skills[i].ID < skills[j].ID
	})

	skillByID := indexSkills(skills)
	skillDirByID := map[string]string{}
	for _, skill := range skills {
		skillDir := normalizeCodexSkillName(skill.ID)
		skillDirByID[skill.ID] = skillDir

		skillDirRel := filepath.ToSlash(filepath.Join(".agents", "skills", skillDir))
		skillFileRel := filepath.ToSlash(filepath.Join(skillDirRel, "SKILL.md"))
		if err := safepath.MkdirAll(root, skillDirRel, 0o755); err != nil {
			return fmt.Errorf("compose codex: %w", err)
		}

		skillDoc := fmt.Sprintf("---\nname: %s\ndescription: %s\n---\n\n<!-- ars:source %s -->\n%s",
			skillDir,
			tomlBasicString(codexSkillDescription(skill)),
			pathOrDefault(skill.Path, filepath.ToSlash(filepath.Join(".ai", "skills", skill.ID, "SKILL.md"))),
			ensureTrailingNewline(skill.Content),
		)
		if err := safepath.WriteFile(root, skillFileRel, []byte(skillDoc), 0o644); err != nil {
			return fmt.Errorf("compose codex: %w", err)
		}

		openAIYamlRel := filepath.ToSlash(filepath.Join(skillDirRel, "agents", "openai.yaml"))
		if err := safepath.MkdirAll(root, filepath.ToSlash(filepath.Join(skillDirRel, "agents")), 0o755); err != nil {
			return fmt.Errorf("compose codex: %w", err)
		}
		openAIYaml := fmt.Sprintf("interface:\n  display_name: %q\n  short_description: %q\npolicy:\n  allow_implicit_invocation: true\n",
			skill.ID,
			codexSkillDescription(skill),
		)
		if err := safepath.WriteFile(root, openAIYamlRel, []byte(openAIYaml), 0o644); err != nil {
			return fmt.Errorf("compose codex: %w", err)
		}
	}

	agents := append([]arslib.Agent(nil), repo.Agents...)
	sort.Slice(agents, func(i, j int) bool {
		return agents[i].ID < agents[j].ID
	})

	for _, agent := range agents {
		name := normalizeCodexAgentName(agent.ID)
		subagentRel := filepath.ToSlash(filepath.Join(".codex", "agents", name+".toml"))
		subagent := buildCodexSubagent(agent, name, skillByID, skillDirByID)
		if err := safepath.WriteFile(root, subagentRel, []byte(subagent), 0o644); err != nil {
			return fmt.Errorf("compose codex: %w", err)
		}
	}

	configRel := ".codex/config.toml"
	config := "[agents]\nmax_threads = 6\nmax_depth = 1\n"
	if err := safepath.WriteFile(root, configRel, []byte(config), 0o644); err != nil {
		return fmt.Errorf("compose codex: %w", err)
	}

	rulesRel := ".codex/rules/ares.rules"
	rules := `# Generated by ars compose --target codex.
# Codex .rules files control command execution outside the sandbox.

prefix_rule(
    pattern = ["rm", "-rf", "/"],
    decision = "forbidden",
    justification = "Blocking destructive root deletion commands.",
    match = ["rm -rf /"],
)

prefix_rule(
    pattern = ["git", "push"],
    decision = "prompt",
    justification = "Require explicit confirmation before pushing changes.",
    match = ["git push", "git push origin main"],
)
`
	if err := safepath.WriteFile(root, rulesRel, []byte(rules), 0o644); err != nil {
		return fmt.Errorf("compose codex: %w", err)
	}

	content := buildCodexRootOutput(repo, skillByID, skillDirByID)

	if err := safepath.WriteFile(root, "AGENTS.md", []byte(content), 0o644); err != nil {
		return fmt.Errorf("compose codex: %w", err)
	}

	return nil
}

func buildCodexRootOutput(repo *arslib.Repository, skillByID map[string]arslib.Skill, skillDirByID map[string]string) string {
	var b strings.Builder
	b.WriteString(arsSourceMarker)
	b.WriteString("# ")
	b.WriteString(repo.Manifest.Project.Name)
	b.WriteString("\n\n")

	instructions := append([]arslib.Instruction(nil), repo.Instructions...)
	sort.Slice(instructions, func(i, j int) bool {
		return instructions[i].ID < instructions[j].ID
	})

	if len(instructions) > 0 {
		b.WriteString("## Repository Instructions\n\n")
		for _, inst := range instructions {
			b.WriteString("<!-- ars:source ")
			b.WriteString(pathOrDefault(inst.Path, filepath.ToSlash(filepath.Join(".ai", "instructions", inst.ID+".md"))))
			b.WriteString(" -->\n")
			b.WriteString(ensureTrailingNewline(inst.Content))
			b.WriteByte('\n')
		}
	}

	if len(skillDirByID) > 0 {
		b.WriteString("## Codex Skills\n\n")
		skillDirs := make([]string, 0, len(skillDirByID))
		for _, dir := range skillDirByID {
			skillDirs = append(skillDirs, dir)
		}
		sort.Strings(skillDirs)
		for _, dir := range skillDirs {
			b.WriteString("- .agents/skills/")
			b.WriteString(dir)
			b.WriteString("/SKILL.md\n")
		}
		b.WriteByte('\n')
	}

	agents := append([]arslib.Agent(nil), repo.Agents...)
	sort.Slice(agents, func(i, j int) bool {
		return agents[i].ID < agents[j].ID
	})

	for _, agent := range agents {
		b.WriteString("## ")
		b.WriteString(strings.ToLower(agent.ID))
		b.WriteString("\n\n")
		b.WriteString("<!-- ars:source ")
		b.WriteString(pathOrDefault(agent.Path, filepath.ToSlash(filepath.Join(".ai", "agents", agent.ID, "AGENT.md"))))
		b.WriteString(" -->\n")
		b.WriteString(ensureTrailingNewline(agent.Content))

		skillRefs := referencedCodexSkillPaths(agent, skillByID, skillDirByID)
		if len(skillRefs) > 0 {
			b.WriteString("\n### Skills\n")
			for _, rel := range skillRefs {
				b.WriteString("- ")
				b.WriteString(rel)
				b.WriteByte('\n')
			}
		}

		b.WriteString("\n### Subagent\n")
		b.WriteString("- .codex/agents/")
		b.WriteString(normalizeCodexAgentName(agent.ID))
		b.WriteString(".toml\n\n")
	}

	return b.String()
}

func referencedCodexSkillPaths(agent arslib.Agent, skills map[string]arslib.Skill, skillDirByID map[string]string) []string {
	seen := map[string]struct{}{}
	out := []string{}
	for _, ref := range agent.SkillRefs {
		skill, ok := resolveSkill(ref, skills)
		if !ok {
			continue
		}
		dir := skillDirByID[skill.ID]
		if dir == "" {
			continue
		}
		rel := filepath.ToSlash(filepath.Join(".agents", "skills", dir, "SKILL.md"))
		if _, ok := seen[rel]; ok {
			continue
		}
		seen[rel] = struct{}{}
		out = append(out, rel)
	}
	sort.Strings(out)
	return out
}

func buildCodexSubagent(agent arslib.Agent, name string, skills map[string]arslib.Skill, skillDirByID map[string]string) string {
	var b strings.Builder
	b.WriteString("name = ")
	b.WriteString(tomlBasicString(name))
	b.WriteByte('\n')
	b.WriteString("description = ")
	b.WriteString(tomlBasicString(subagentDescription(agent.Content, name)))
	b.WriteByte('\n')
	b.WriteString("model = \"gpt-5.3-codex\"\n")
	b.WriteString("model_reasoning_effort = ")
	b.WriteString(tomlBasicString(codexReasoningEffort(name)))
	b.WriteByte('\n')
	b.WriteString("sandbox_mode = ")
	b.WriteString(tomlBasicString(codexSandboxMode(name)))
	b.WriteByte('\n')

	b.WriteString("developer_instructions = \"\"\"\n")
	b.WriteString("Source: ")
	b.WriteString(pathOrDefault(agent.Path, filepath.ToSlash(filepath.Join(".ai", "agents", agent.ID, "AGENT.md"))))
	b.WriteString("\n\n")
	b.WriteString(strings.TrimSpace(agent.Content))

	skillRefs := referencedCodexSkillPaths(agent, skills, skillDirByID)
	if len(skillRefs) > 0 {
		b.WriteString("\n\nSkills to use when relevant:\n")
		for _, rel := range skillRefs {
			b.WriteString("- ")
			b.WriteString(rel)
			b.WriteByte('\n')
		}
	}

	b.WriteString("\"\"\"\n")
	return b.String()
}

func codexReasoningEffort(name string) string {
	lower := strings.ToLower(name)
	if strings.Contains(lower, "architect") || strings.Contains(lower, "planner") || strings.Contains(lower, "review") {
		return "high"
	}
	return "medium"
}

func codexSandboxMode(name string) string {
	lower := strings.ToLower(name)
	if strings.Contains(lower, "architect") || strings.Contains(lower, "planner") || strings.Contains(lower, "review") || strings.Contains(lower, "explorer") || strings.Contains(lower, "docs") {
		return "read-only"
	}
	return "workspace-write"
}

func normalizeCodexSkillName(id string) string {
	raw := strings.ToLower(strings.TrimSpace(id))
	if raw == "" {
		return "skill"
	}
	var b strings.Builder
	lastDash := false
	for _, r := range raw {
		isAlpha := r >= 'a' && r <= 'z'
		isDigit := r >= '0' && r <= '9'
		if isAlpha || isDigit {
			b.WriteRune(r)
			lastDash = false
			continue
		}
		if !lastDash {
			b.WriteByte('-')
			lastDash = true
		}
	}
	name := strings.Trim(b.String(), "-")
	if name == "" {
		name = "skill"
	}
	if len(name) > 64 {
		name = strings.Trim(name[:64], "-")
		if name == "" {
			name = "skill"
		}
	}
	return name
}

func normalizeCodexAgentName(id string) string {
	return normalizeCodexSkillName(id)
}

func codexSkillDescription(skill arslib.Skill) string {
	sections, err := markdown.ExtractSections([]byte(skill.Content))
	if err == nil {
		if purpose, ok := markdown.FindSection(sections, "Purpose"); ok {
			line := strings.TrimSpace(strings.SplitN(purpose.Content, "\n", 2)[0])
			if line != "" {
				return trimToMax(line, 1024)
			}
		}
	}
	return trimToMax(fmt.Sprintf("Reusable workflow for %s tasks. Use when relevant.", skill.ID), 1024)
}

func tomlBasicString(s string) string {
	s = strings.ReplaceAll(s, "\\", "\\\\")
	s = strings.ReplaceAll(s, "\"", "\\\"")
	return fmt.Sprintf("\"%s\"", s)
}
