package compose

import (
	"fmt"
	"path/filepath"
	"sort"
	"strings"

	"github.com/ars-standard/ars/internal/safepath"
	"github.com/ars-standard/ars/pkg/arslib"
)

const copilotGeneratedHeader = "<!-- Generated by ars compose --target copilot. Source: .ai/ -->\n"

// CopilotComposer writes .github/copilot-instructions.md from a Repository.
type CopilotComposer struct{}

func (c *CopilotComposer) Target() string {
	return "copilot"
}

func (c *CopilotComposer) Compose(root string, repo *arslib.Repository) error {
	if repo == nil {
		return fmt.Errorf("compose copilot: repository is nil")
	}

	if _, err := safepath.Join(root, ".github", "copilot-instructions.md"); err != nil {
		return fmt.Errorf("compose copilot: %w", err)
	}

	content := buildCopilotOutput(repo)
	rel := filepath.ToSlash(filepath.Join(".github", "copilot-instructions.md"))
	if err := safepath.WriteFile(root, rel, []byte(content), 0o644); err != nil {
		return fmt.Errorf("compose copilot: %w", err)
	}

	return nil
}

func buildCopilotOutput(repo *arslib.Repository) string {
	var b strings.Builder
	b.WriteString(copilotGeneratedHeader)
	b.WriteString("\n# ")
	b.WriteString(repo.Manifest.Project.Name)
	b.WriteString("\n\n")

	instructions := append([]arslib.Instruction(nil), repo.Instructions...)
	sort.Slice(instructions, func(i, j int) bool {
		return instructions[i].ID < instructions[j].ID
	})

	if len(instructions) > 0 {
		b.WriteString("## Repository Instructions\n\n")
		for _, inst := range instructions {
			b.WriteString(inst.Content)
			if !strings.HasSuffix(inst.Content, "\n") {
				b.WriteByte('\n')
			}
			b.WriteByte('\n')
		}
	}

	skillByID := indexSkills(repo.Skills)
	agents := append([]arslib.Agent(nil), repo.Agents...)
	sort.Slice(agents, func(i, j int) bool {
		return agents[i].ID < agents[j].ID
	})

	for _, agent := range agents {
		b.WriteString(copilotAgentSection(agent, skillByID))
		b.WriteByte('\n')
	}

	return b.String()
}

func copilotAgentSection(agent arslib.Agent, skills map[string]arslib.Skill) string {
	var b strings.Builder
	b.WriteString("## Agent: ")
	b.WriteString(agent.ID)
	b.WriteString("\n\n")
	b.WriteString(buildAgentRule(agent, skills))
	return b.String()
}
