package compose

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/ars-standard/ars/pkg/arslib"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func TestCopilotComposer_HeaderPresent(t *testing.T) {
	root := t.TempDir()
	repo := &arslib.Repository{
		Manifest: arslib.Manifest{Project: arslib.Project{Name: "demo"}},
	}

	require.NoError(t, (&CopilotComposer{}).Compose(root, repo))

	data, err := os.ReadFile(filepath.Join(root, ".github", "copilot-instructions.md"))
	require.NoError(t, err)
	assert.Contains(t, string(data), "<!-- Generated by ars")
}

func TestCopilotComposer_AllAgentsIncluded(t *testing.T) {
	root := t.TempDir()
	repo := &arslib.Repository{
		Manifest: arslib.Manifest{Project: arslib.Project{Name: "demo"}},
		Agents: []arslib.Agent{
			{ID: "alpha", Content: "alpha body"},
			{ID: "beta", Content: "beta body"},
		},
	}

	require.NoError(t, (&CopilotComposer{}).Compose(root, repo))

	data, err := os.ReadFile(filepath.Join(root, ".github", "copilot-instructions.md"))
	require.NoError(t, err)
	body := string(data)
	assert.Equal(t, 2, strings.Count(body, "## Agent:"))
	assert.Contains(t, body, "## Agent: alpha")
	assert.Contains(t, body, "## Agent: beta")
}

func TestCopilotComposer_SkillInlined(t *testing.T) {
	root := t.TempDir()
	repo := &arslib.Repository{
		Manifest: arslib.Manifest{Project: arslib.Project{Name: "demo"}},
		Agents: []arslib.Agent{{
			ID:        "architect",
			Content:   "## Responsibilities\nDesign systems.\n",
			SkillRefs: []string{"skills/architecture-management/SKILL.md"},
		}},
		Skills: []arslib.Skill{{
			ID:      "architecture-management",
			Content: "Architecture skill body.",
		}},
	}

	require.NoError(t, (&CopilotComposer{}).Compose(root, repo))

	data, err := os.ReadFile(filepath.Join(root, ".github", "copilot-instructions.md"))
	require.NoError(t, err)
	body := string(data)
	agentIdx := strings.Index(body, "## Agent: architect")
	require.GreaterOrEqual(t, agentIdx, 0)
	agentSection := body[agentIdx:]
	assert.Contains(t, agentSection, "Architecture skill body.")
}

func TestCopilotComposer_Idempotent(t *testing.T) {
	root := t.TempDir()
	repo := &arslib.Repository{
		Manifest: arslib.Manifest{Project: arslib.Project{Name: "demo"}},
		Instructions: []arslib.Instruction{{
			ID:      "rules",
			Content: "Repository rules.",
		}},
		Agents: []arslib.Agent{{
			ID:      "planner",
			Content: "Plans work.",
		}},
	}

	composer := &CopilotComposer{}
	require.NoError(t, composer.Compose(root, repo))

	path := filepath.Join(root, ".github", "copilot-instructions.md")
	first, err := os.ReadFile(path)
	require.NoError(t, err)

	require.NoError(t, composer.Compose(root, repo))
	second, err := os.ReadFile(path)
	require.NoError(t, err)

	assert.Equal(t, first, second)
}

func TestCopilotComposer_EmptyInstructions(t *testing.T) {
	root := t.TempDir()
	repo := &arslib.Repository{
		Manifest: arslib.Manifest{Project: arslib.Project{Name: "demo"}},
		Agents: []arslib.Agent{{
			ID:      "planner",
			Content: "Plans work.",
		}},
	}

	require.NoError(t, (&CopilotComposer{}).Compose(root, repo))

	data, err := os.ReadFile(filepath.Join(root, ".github", "copilot-instructions.md"))
	require.NoError(t, err)
	body := string(data)
	assert.NotContains(t, body, "## Repository Instructions")
	assert.Contains(t, body, copilotGeneratedHeader)
	assert.Contains(t, body, "## Agent: planner")
}

func TestCopilotAgentSection(t *testing.T) {
	agent := arslib.Agent{
		ID:      "planner",
		Content: "## Role\nPlans.\n",
	}
	section := copilotAgentSection(agent, nil)
	assert.Contains(t, section, "## Agent: planner")
	assert.Contains(t, section, "## Role")
}
