package compose

import (
	"strings"
	"testing"

	"github.com/okfriansyah-moh/ares/internal/safepath"
	"github.com/okfriansyah-moh/ares/pkg/arslib"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func TestCopilotComposer_HeaderPresent(t *testing.T) {
	root := t.TempDir()
	repo := &arslib.Repository{
		Manifest: arslib.Manifest{Project: arslib.Project{Name: "demo"}},
		Instructions: []arslib.Instruction{{
			ID:      "repo",
			Path:    ".ai/instructions/repo.md",
			Content: "Repository rules.\n",
		}},
		Skills: []arslib.Skill{{
			ID:      "task-implementation",
			Path:    ".ai/skills/task-implementation/SKILL.md",
			Content: "# Task Implementation\n\n## Purpose\nImplement one task at a time.\n",
		}},
		Prompts: []arslib.Prompt{{
			ID:      "create-plan",
			Path:    ".ai/prompts/create-plan.md",
			Content: "Create a detailed implementation plan.\n",
		}},
		Agents: []arslib.Agent{{
			ID:      "planner",
			Path:    ".ai/agents/planner/AGENT.md",
			Content: "## Role\nPlans work.\n",
			SkillRefs: []string{
				"skills/task-implementation/SKILL.md",
			},
		}},
	}

	require.NoError(t, (&CopilotComposer{}).Compose(root, repo))

	data, err := safepath.ReadFile(root, ".github/copilot-instructions.md")
	require.NoError(t, err)
	assert.Contains(t, string(data), "<!-- Generated by ars")
	assert.Contains(t, string(data), ".github/skills/*/SKILL.md")

	instructionData, err := safepath.ReadFile(root, ".github/instructions/repo.instructions.md")
	require.NoError(t, err)
	assert.Contains(t, string(instructionData), "applyTo: \"**\"")

	skillData, err := safepath.ReadFile(root, ".github/skills/task-implementation/SKILL.md")
	require.NoError(t, err)
	assert.Contains(t, string(skillData), "name: task-implementation")
	assert.Contains(t, string(skillData), "description:")

	promptData, err := safepath.ReadFile(root, ".github/prompts/create-plan.prompt.md")
	require.NoError(t, err)
	assert.Contains(t, string(promptData), "description:")
	assert.NotContains(t, string(promptData), "mode:")
	assert.NotContains(t, string(promptData), "<!-- ars:source")

	agentData, err := safepath.ReadFile(root, ".github/agents/planner.agent.md")
	require.NoError(t, err)
	assert.Contains(t, string(agentData), "target: github-copilot")
	assert.Contains(t, string(agentData), "name: planner")
}

func TestCopilotComposer_AllAgentsIncluded(t *testing.T) {
	root := t.TempDir()
	repo := &arslib.Repository{
		Manifest: arslib.Manifest{Project: arslib.Project{Name: "demo"}},
		Agents: []arslib.Agent{
			{ID: "alpha", Content: "alpha body"},
			{ID: "beta", Content: "beta body"},
		},
	}

	require.NoError(t, (&CopilotComposer{}).Compose(root, repo))

	data, err := safepath.ReadFile(root, ".github/copilot-instructions.md")
	require.NoError(t, err)
	body := string(data)
	assert.Equal(t, 2, strings.Count(body, "## Agent:"))
	assert.Contains(t, body, "## Agent: alpha")
	assert.Contains(t, body, "## Agent: beta")
}

func TestCopilotComposer_SkillInlined(t *testing.T) {
	root := t.TempDir()
	repo := &arslib.Repository{
		Manifest: arslib.Manifest{Project: arslib.Project{Name: "demo"}},
		Agents: []arslib.Agent{{
			ID:        "architect",
			Path:      ".ai/agents/architect/AGENT.md",
			Content:   "## Responsibilities\nDesign systems.\n",
			SkillRefs: []string{"skills/architecture-management/SKILL.md"},
		}},
		Skills: []arslib.Skill{{
			ID:      "architecture-management",
			Path:    ".ai/skills/architecture-management/SKILL.md",
			Content: "Architecture skill body.",
		}},
	}

	require.NoError(t, (&CopilotComposer{}).Compose(root, repo))

	data, err := safepath.ReadFile(root, ".github/copilot-instructions.md")
	require.NoError(t, err)
	body := string(data)
	agentIdx := strings.Index(body, "## Agent: architect")
	require.GreaterOrEqual(t, agentIdx, 0)
	agentSection := body[agentIdx:]
	assert.Contains(t, agentSection, "Architecture skill body.")

	agentProfile, err := safepath.ReadFile(root, ".github/agents/architect.agent.md")
	require.NoError(t, err)
	assert.Contains(t, string(agentProfile), "Architecture skill body.")
}

func TestCopilotComposer_Idempotent(t *testing.T) {
	root := t.TempDir()
	repo := &arslib.Repository{
		Manifest: arslib.Manifest{Project: arslib.Project{Name: "demo"}},
		Instructions: []arslib.Instruction{{
			ID:      "rules",
			Content: "Repository rules.",
		}},
		Agents: []arslib.Agent{{
			ID:      "planner",
			Path:    ".ai/agents/planner/AGENT.md",
			Content: "Plans work.",
		}},
		Prompts: []arslib.Prompt{{
			ID:      "plan",
			Path:    ".ai/prompts/plan.md",
			Content: "Plan this change.",
		}},
	}

	composer := &CopilotComposer{}
	require.NoError(t, composer.Compose(root, repo))

	first, err := safepath.ReadFile(root, ".github/copilot-instructions.md")
	require.NoError(t, err)

	require.NoError(t, composer.Compose(root, repo))
	second, err := safepath.ReadFile(root, ".github/copilot-instructions.md")
	require.NoError(t, err)

	assert.Equal(t, first, second)
}

func TestCopilotComposer_EmptyInstructions(t *testing.T) {
	root := t.TempDir()
	repo := &arslib.Repository{
		Manifest: arslib.Manifest{Project: arslib.Project{Name: "demo"}},
		Agents: []arslib.Agent{{
			ID:      "planner",
			Path:    ".ai/agents/planner/AGENT.md",
			Content: "Plans work.",
		}},
	}

	require.NoError(t, (&CopilotComposer{}).Compose(root, repo))

	data, err := safepath.ReadFile(root, ".github/copilot-instructions.md")
	require.NoError(t, err)
	body := string(data)
	assert.NotContains(t, body, "## Repository Instructions")
	assert.Contains(t, body, copilotGeneratedHeader)
	assert.Contains(t, body, "## Agent: planner")
}

func TestCopilotAgentSection(t *testing.T) {
	agent := arslib.Agent{
		ID:      "planner",
		Path:    ".ai/agents/planner/AGENT.md",
		Content: "## Role\nPlans.\n",
	}
	section := copilotAgentSection(agent, nil)
	assert.Contains(t, section, "## Agent: planner")
	assert.Contains(t, section, "## Role")
}

func TestNormalizeCopilotName(t *testing.T) {
	assert.Equal(t, "plan-management", normalizeCopilotName("Plan_Management"))
	assert.Equal(t, "item", normalizeCopilotName("***"))
}

func TestCopilotComposer_FailsOnInstructionNameCollision(t *testing.T) {
	root := t.TempDir()
	repo := &arslib.Repository{
		Manifest: arslib.Manifest{Project: arslib.Project{Name: "demo"}},
		Instructions: []arslib.Instruction{
			{ID: "Plan_Management", Content: "one"},
			{ID: "plan-management", Content: "two"},
		},
	}

	err := (&CopilotComposer{}).Compose(root, repo)
	require.Error(t, err)
	assert.Contains(t, err.Error(), "compose copilot: instruction id")
	assert.Contains(t, err.Error(), "normalizes to \"plan-management\"")
}

func TestCopilotComposer_FailsOnSkillNameCollision(t *testing.T) {
	root := t.TempDir()
	repo := &arslib.Repository{
		Manifest: arslib.Manifest{Project: arslib.Project{Name: "demo"}},
		Skills: []arslib.Skill{
			{ID: "Task_Review", Content: "first"},
			{ID: "task-review", Content: "second"},
		},
	}

	err := (&CopilotComposer{}).Compose(root, repo)
	require.Error(t, err)
	assert.Contains(t, err.Error(), "compose copilot: skill id")
	assert.Contains(t, err.Error(), "normalizes to \"task-review\"")
}
