package importer

import (
	"path/filepath"
	"testing"

	"github.com/okfriansyah-moh/ares/internal/safepath"
	"github.com/okfriansyah-moh/ares/pkg/arslib"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

const sampleCopilot = `<!-- Generated by ars compose --target copilot. Source: .ai/ -->

# demo

## Repository Instructions

Global repository rules.

## Agent: planner

## Role
Plans work.

## Agent: reviewer

Reviews changes.
`

func writeCopilotFile(t *testing.T, root, content string) {
	t.Helper()
	require.NoError(t, safepath.WriteFile(root, ".github/copilot-instructions.md", []byte(content), 0o644))
}

func TestGitHubImporter_BasicParse(t *testing.T) {
	root := t.TempDir()
	writeCopilotFile(t, root, `<!-- Generated by ars compose --target copilot. Source: .ai/ -->

# demo

## Repository Instructions

Global repository rules.

## Agent: planner

## Role
Plans work.

## Uses
- skills/task-implementation/SKILL.md

## Agent: reviewer

Reviews changes.
`)

	repo, err := (&GitHubImporter{}).Import(root)
	require.NoError(t, err)
	require.Len(t, repo.Agents, 2)
	assert.Equal(t, "planner", repo.Agents[0].ID)
	assert.Contains(t, repo.Agents[0].Content, "Plans work.")
	assert.Equal(t, []string{"skills/task-implementation/SKILL.md"}, repo.Agents[0].SkillRefs)
}

func TestGitHubImporter_InstructionSections(t *testing.T) {
	root := t.TempDir()
	writeCopilotFile(t, root, sampleCopilot)

	repo, err := (&GitHubImporter{}).Import(root)
	require.NoError(t, err)
	require.NotEmpty(t, repo.Instructions)

	found := false
	for _, inst := range repo.Instructions {
		if inst.ID == "repository-instructions" {
			found = true
			assert.Contains(t, inst.Content, "Global repository rules")
		}
	}
	assert.True(t, found)
	assert.Equal(t, "demo", repo.Manifest.Project.Name)
}

func TestGitHubImporter_SkipsEmptyInstructionSections(t *testing.T) {
	root := t.TempDir()
	writeCopilotFile(t, root, `# demo

## Architecture Invariants

<!-- ars:source .ai/instructions/architecture-invariants.md -->

## Repository Instructions

Keep changes scoped.
`)

	repo, err := (&GitHubImporter{}).Import(root)
	require.NoError(t, err)
	require.Len(t, repo.Instructions, 1)
	assert.Equal(t, "repository-instructions", repo.Instructions[0].ID)
	assert.Contains(t, repo.Instructions[0].Content, "Keep changes scoped")
}

func TestGitHubImporter_SkipsEmptyStructuredInstructions(t *testing.T) {
	root := t.TempDir()
	require.NoError(t, safepath.WriteFile(root, ".github/instructions/architecture-invariants.instructions.md", []byte(`---
applyTo: "**"
---

<!-- ars:source .ai/instructions/architecture-invariants.md -->
`), 0o644))
	require.NoError(t, safepath.WriteFile(root, ".github/instructions/repo.instructions.md", []byte(`---
applyTo: "**"
---

Keep changes scoped.
`), 0o644))

	repo, err := (&GitHubImporter{}).Import(root)
	require.NoError(t, err)
	require.Len(t, repo.Instructions, 1)
	assert.Equal(t, "repo", repo.Instructions[0].ID)
}

func TestGitHubImporter_PreservesReadableInstructionBoundaries(t *testing.T) {
	root := t.TempDir()
	writeCopilotFile(t, root, `# demo

## Repository Instructions

Design before code - brainstorming skill
Vertical slice per module - .github/skills/vertical-slice/SKILL.md
Commands and todo requirements: AGENTS.md Validation Requirement.
Use rtk for verbose command output.
`)

	repo, err := (&GitHubImporter{}).Import(root)
	require.NoError(t, err)
	require.Len(t, repo.Instructions, 1)

	content := repo.Instructions[0].Content
	assert.Contains(t, content, "skill\nVertical slice")
	assert.Contains(t, content, "Requirement.\nUse rtk")
	assert.NotContains(t, content, "skillVertical")
	assert.NotContains(t, content, "Requirement.Use")
}

func TestGitHubImporter_MissingFile(t *testing.T) {
	root := t.TempDir()

	_, err := (&GitHubImporter{}).Import(root)
	require.Error(t, err)
	assert.Contains(t, err.Error(), "copilot artifacts not found")
}

func TestGitHubImporter_SlugCollision(t *testing.T) {
	root := t.TempDir()
	content := `# demo

## Agent: Same

First agent.

## Agent: Same

Second agent.
`
	writeCopilotFile(t, root, content)

	repo, err := (&GitHubImporter{}).Import(root)
	require.NoError(t, err)
	require.Len(t, repo.Agents, 2)
	assert.Equal(t, "same", repo.Agents[0].ID)
	assert.Equal(t, "same-2", repo.Agents[1].ID)
}

func TestWriteRepository_SkipExisting(t *testing.T) {
	root := t.TempDir()
	repo := &arslib.Repository{
		Manifest: arslib.Manifest{
			Version: "2.0",
			Project: arslib.Project{Name: "demo"},
		},
		Instructions: []arslib.Instruction{{
			ID:      "rules",
			Content: "new content",
		}},
	}

	require.NoError(t, safepath.WriteFile(root, ".ai/instructions/rules.md", []byte("keep me"), 0o644))

	created, conflicts, err := WriteRepository(root, repo, false)
	require.NoError(t, err)
	assert.Equal(t, 1, conflicts)
	assert.Equal(t, 1, created) // manifest only

	data, err := safepath.ReadFile(root, ".ai/instructions/rules.md")
	require.NoError(t, err)
	assert.Equal(t, "keep me", string(data))
}

func TestWriteRepository_Overwrite(t *testing.T) {
	root := t.TempDir()
	repo := &arslib.Repository{
		Manifest: arslib.Manifest{
			Version: "2.0",
			Project: arslib.Project{Name: "demo"},
		},
		Instructions: []arslib.Instruction{{
			ID:      "rules",
			Content: "new content",
		}},
	}

	require.NoError(t, safepath.WriteFile(root, ".ai/instructions/rules.md", []byte("old"), 0o644))

	created, conflicts, err := WriteRepository(root, repo, true)
	require.NoError(t, err)
	assert.Equal(t, 0, conflicts)
	assert.Equal(t, 2, created)

	data, err := safepath.ReadFile(root, ".ai/instructions/rules.md")
	require.NoError(t, err)
	assert.Equal(t, "new content", string(data))
}

func TestWriteRepository_SkipsEmptyContentFiles(t *testing.T) {
	root := t.TempDir()
	repo := &arslib.Repository{
		Manifest: arslib.Manifest{
			Version: "2.0",
			Project: arslib.Project{Name: "demo"},
		},
		Instructions: []arslib.Instruction{
			{ID: "empty-instruction", Content: " \n\t"},
			{ID: "repo", Content: "Repository rules."},
		},
		Agents: []arslib.Agent{
			{ID: "empty-agent", Content: "\n"},
		},
		Skills: []arslib.Skill{
			{ID: "empty-skill", Content: ""},
		},
		Prompts: []arslib.Prompt{
			{ID: "empty-prompt", Content: ""},
		},
	}

	created, conflicts, err := WriteRepository(root, repo, false)
	require.NoError(t, err)
	assert.Equal(t, 0, conflicts)
	assert.Equal(t, 2, created) // non-empty instruction + manifest

	require.FileExists(t, filepath.Join(root, ".ai", "instructions", "repo.md"))
	require.NoFileExists(t, filepath.Join(root, ".ai", "instructions", "empty-instruction.md"))
	require.NoFileExists(t, filepath.Join(root, ".ai", "agents", "empty-agent", "AGENT.md"))
	require.NoFileExists(t, filepath.Join(root, ".ai", "skills", "empty-skill", "SKILL.md"))
	require.NoFileExists(t, filepath.Join(root, ".ai", "prompts", "empty-prompt.md"))
}

func TestImport_UnknownSource(t *testing.T) {
	_, err := Import(t.TempDir(), "unknown")
	require.Error(t, err)
	assert.ErrorIs(t, err, ErrUnknownSource)
}

func TestSlugify(t *testing.T) {
	assert.Equal(t, "planner", slugify("Agent: planner"))
	assert.Equal(t, "my-skill", slugify("Skill: My Skill"))
}

func TestGitHubImporter_ImportsStructuredDirectories(t *testing.T) {
	root := t.TempDir()

	require.NoError(t, safepath.WriteFile(root, ".github/instructions/repo.instructions.md", []byte(`---
applyTo: "**"
---

<!-- ars:source .ai/instructions/repo.md -->
Keep changes scoped.
`), 0o644))

	require.NoError(t, safepath.WriteFile(root, ".github/skills/task-implementation/SKILL.md", []byte(`---
name: task-implementation
description: "Implement tasks."
---

<!-- ars:source .ai/skills/task-implementation/SKILL.md -->
# Task Implementation
`), 0o644))

	require.NoError(t, safepath.WriteFile(root, ".github/prompts/review-task.prompt.md", []byte(`---
mode: ask
description: "Review a task"
---

<!-- ars:source .ai/prompts/review-task.md -->
# Review Task
`), 0o644))

	require.NoError(t, safepath.WriteFile(root, ".github/agents/planner.agent.md", []byte(`---
name: planner
description: "Plans work"
target: github-copilot
---

<!-- ars:source .ai/agents/planner/AGENT.md -->
## Role
Plans implementation tasks.

## Uses
- skills/task-implementation/SKILL.md
`), 0o644))

	repo, err := (&GitHubImporter{}).Import(root)
	require.NoError(t, err)

	require.Len(t, repo.Instructions, 1)
	assert.Equal(t, "repo", repo.Instructions[0].ID)
	assert.Contains(t, repo.Instructions[0].Content, "Keep changes scoped")

	require.Len(t, repo.Skills, 1)
	assert.Equal(t, "task-implementation", repo.Skills[0].ID)

	require.Len(t, repo.Prompts, 1)
	assert.Equal(t, "review-task", repo.Prompts[0].ID)

	require.Len(t, repo.Agents, 1)
	assert.Equal(t, "planner", repo.Agents[0].ID)
	assert.Contains(t, repo.Agents[0].Content, "Plans implementation tasks")
	assert.Equal(t, []string{"skills/task-implementation/SKILL.md"}, repo.Agents[0].SkillRefs)
}

func TestGitHubImporter_SkillExtraFiles(t *testing.T) {
	root := t.TempDir()

	require.NoError(t, safepath.WriteFile(root, ".github/skills/plan-management/SKILL.md", []byte(`---
name: plan-management
description: "Manage plans."
---

# Plan Management
`), 0o644))
	require.NoError(t, safepath.WriteFile(root, ".github/skills/plan-management/reference/reference.md",
		[]byte("# Reference\nDetailed reference content.\n"), 0o644))

	repo, err := (&GitHubImporter{}).Import(root)
	require.NoError(t, err)

	require.Len(t, repo.Skills, 1)
	assert.Equal(t, "plan-management", repo.Skills[0].ID)
	require.Len(t, repo.Skills[0].ExtraFiles, 1)
	assert.Equal(t, "reference/reference.md", repo.Skills[0].ExtraFiles[0].Rel)
	assert.Contains(t, string(repo.Skills[0].ExtraFiles[0].Content), "Detailed reference content.")
}

func TestWriteRepository_WritesSkillExtraFiles(t *testing.T) {
	root := t.TempDir()
	repo := &arslib.Repository{
		Manifest: arslib.Manifest{
			Version: "2.0",
			Project: arslib.Project{Name: "demo"},
		},
		Skills: []arslib.Skill{{
			ID:      "plan-management",
			Content: "# Plan Management\n",
			ExtraFiles: []arslib.ExtraFile{
				{Rel: "reference/reference.md", Content: []byte("# Reference\n")},
			},
		}},
	}

	created, conflicts, err := WriteRepository(root, repo, true)
	require.NoError(t, err)
	assert.Equal(t, 0, conflicts)
	assert.Equal(t, 3, created) // SKILL.md + extra file + manifest

	data, err := safepath.ReadFile(root, ".ai/skills/plan-management/reference/reference.md")
	require.NoError(t, err)
	assert.Equal(t, "# Reference\n", string(data))
}

func TestWriteRepository_WritesPrompts(t *testing.T) {
	root := t.TempDir()
	repo := &arslib.Repository{
		Manifest: arslib.Manifest{
			Version: "2.0",
			Project: arslib.Project{Name: "demo"},
		},
		Prompts: []arslib.Prompt{{
			ID:      "create-plan",
			Content: "Create a plan.",
		}},
	}

	created, conflicts, err := WriteRepository(root, repo, true)
	require.NoError(t, err)
	assert.Equal(t, 2, created)
	assert.Equal(t, 0, conflicts)

	data, err := safepath.ReadFile(root, filepath.ToSlash(filepath.Join(".ai", "prompts", "create-plan.md")))
	require.NoError(t, err)
	assert.Equal(t, "Create a plan.", string(data))
}
