package importer

import (
	"testing"

	"github.com/ars-standard/ars/internal/safepath"
	"github.com/ars-standard/ars/pkg/arslib"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

const sampleCopilot = `<!-- Generated by ars compose --target copilot. Source: .ai/ -->

# demo

## Repository Instructions

Global repository rules.

## Agent: planner

## Role
Plans work.

## Agent: reviewer

Reviews changes.
`

func writeCopilotFile(t *testing.T, root, content string) {
	t.Helper()
	require.NoError(t, safepath.WriteFile(root, ".github/copilot-instructions.md", []byte(content), 0o644))
}

func TestGitHubImporter_BasicParse(t *testing.T) {
	root := t.TempDir()
	writeCopilotFile(t, root, sampleCopilot)

	repo, err := (&GitHubImporter{}).Import(root)
	require.NoError(t, err)
	require.Len(t, repo.Agents, 2)
	assert.Equal(t, "planner", repo.Agents[0].ID)
	assert.Contains(t, repo.Agents[0].Content, "Plans work.")
}

func TestGitHubImporter_InstructionSections(t *testing.T) {
	root := t.TempDir()
	writeCopilotFile(t, root, sampleCopilot)

	repo, err := (&GitHubImporter{}).Import(root)
	require.NoError(t, err)
	require.NotEmpty(t, repo.Instructions)

	found := false
	for _, inst := range repo.Instructions {
		if inst.ID == "repository-instructions" {
			found = true
			assert.Contains(t, inst.Content, "Global repository rules")
		}
	}
	assert.True(t, found)
	assert.Equal(t, "demo", repo.Manifest.Project.Name)
}

func TestGitHubImporter_MissingFile(t *testing.T) {
	root := t.TempDir()

	_, err := (&GitHubImporter{}).Import(root)
	require.Error(t, err)
	assert.Contains(t, err.Error(), "copilot-instructions.md not found")
}

func TestGitHubImporter_SlugCollision(t *testing.T) {
	root := t.TempDir()
	content := `# demo

## Agent: Same

First agent.

## Agent: Same

Second agent.
`
	writeCopilotFile(t, root, content)

	repo, err := (&GitHubImporter{}).Import(root)
	require.NoError(t, err)
	require.Len(t, repo.Agents, 2)
	assert.Equal(t, "same", repo.Agents[0].ID)
	assert.Equal(t, "same-2", repo.Agents[1].ID)
}

func TestWriteRepository_SkipExisting(t *testing.T) {
	root := t.TempDir()
	repo := &arslib.Repository{
		Manifest: arslib.Manifest{
			Version: "2.0",
			Project: arslib.Project{Name: "demo"},
		},
		Instructions: []arslib.Instruction{{
			ID:      "rules",
			Content: "new content",
		}},
	}

	require.NoError(t, safepath.WriteFile(root, ".ai/instructions/rules.md", []byte("keep me"), 0o644))

	created, conflicts, err := WriteRepository(root, repo, false)
	require.NoError(t, err)
	assert.Equal(t, 1, conflicts)
	assert.Equal(t, 1, created) // manifest only

	data, err := safepath.ReadFile(root, ".ai/instructions/rules.md")
	require.NoError(t, err)
	assert.Equal(t, "keep me", string(data))
}

func TestWriteRepository_Overwrite(t *testing.T) {
	root := t.TempDir()
	repo := &arslib.Repository{
		Manifest: arslib.Manifest{
			Version: "2.0",
			Project: arslib.Project{Name: "demo"},
		},
		Instructions: []arslib.Instruction{{
			ID:      "rules",
			Content: "new content",
		}},
	}

	require.NoError(t, safepath.WriteFile(root, ".ai/instructions/rules.md", []byte("old"), 0o644))

	created, conflicts, err := WriteRepository(root, repo, true)
	require.NoError(t, err)
	assert.Equal(t, 0, conflicts)
	assert.Equal(t, 2, created)

	data, err := safepath.ReadFile(root, ".ai/instructions/rules.md")
	require.NoError(t, err)
	assert.Equal(t, "new content", string(data))
}

func TestImport_UnknownSource(t *testing.T) {
	_, err := Import(t.TempDir(), "unknown")
	require.Error(t, err)
	assert.ErrorIs(t, err, ErrUnknownSource)
}

func TestSlugify(t *testing.T) {
	assert.Equal(t, "planner", slugify("Agent: planner"))
	assert.Equal(t, "my-skill", slugify("Skill: My Skill"))
}
